---
title: "10-other_explainers"
author: "Katherine Goode"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

I recently started looking into new papers that cited LIME. This journal contains some information on papers with explainers developed after LIME.

# LORE (LOcal Rule-based Explanations)

This section contains my notes from reading through the paper introduction [LORE](https://arxiv.org/pdf/1805.10820.pdf). 

Same idea as LIME: whole decision boundary is complex, but simpler at a local level

Difference from LIME:

(1) obtain the local data in a different way from LIME using a "genetic algorithm"
(2) better explainations (they claim)

## Method

Notation from the paper: 

- $b$ = black blox predictor
- $x$ = specific instance in the data
- $y$ = predicted value from $b$ given $x$
- $c$ = interpretable predictor (a decision tree)
- $N$ = number of neighbor instances of $x$ generated using a "genetic algorithm"
- $r$ = the single rule that is a part of the local explanation
- $\Phi$ = the counterfactual rules that are a part of the local explanation
- $Z$ = generated instances with characteristics close to the ones of $x$ (note that $Z=Z_{=}\cup Z_{\not=}$)
- $Z_=$ = set of instances $z\in Z$ where $b(z)=b(x)$ 
- $Z_{\not=}$ =  set of instances $z\in Z$ where $b(z)\not=b(x)$ 

General Idea:

- generate neighboring instances ($Z$) to $x$ using a genetic algorithm
- fit a tree to $Z$ called $c$
- obtain the local explainer $r$ by extracting the path from the decision tree $c$ that leads to $y$ with the same conditions as $x$
- obtain the counterfactual rules $\Phi$ using the other paths from the decision tree $c$

Genetic Algorithm: Makes use of fitness functions

Fitness function = A fitness function is a particular type of objective function that is used to summarise, as a single figure of merit, how close a given design solution is to achieving the set aims. Fitness functions are used in genetic programming and genetic algorithms to guide simulations towards optimal design solutions. (from Wikipedia)