---
title: "10-compring-rfs"
author: "Katherine Goode"
date: "9/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(randomForest)
library(stringr)

CCFs_withlands = read.csv("../../../diagnostics-paper/data/raw/CCFs_withlands.csv")

includes <-
  setdiff(
    names(CCFs_withlands),
    c(
      "compare_id",
      "profile1_id",
      "profile2_id",
      "study.x",
      "study.y",
      "barrel.x",
      "barrel.y",
      "bullet.x",
      "bullet.y",
      "land.x",
      "land.y",
      "land_id.x",
      "land_id.y",
      "signature_length",
      "lag",
      "overlap"
    )
  )

set.seed(20170222)
rtrees3 <-
  randomForest(factor(match) ~ ., data = CCFs_withlands[, includes], ntree = 300)

set.seed(20140501)
rtrees2 <-
  randomForest(factor(match) ~ ., data = CCFs_withlands[, includes], ntree = 300)

# plot votes in a scatterplot
plot(rtrees2$votes, rtrees3$votes)
plot(rtrees2$votes[,2], bulletxtrctr::rtrees$votes[,2])
plot(rtrees3$votes[,2], bulletxtrctr::rtrees$votes[,2])

plot(sort(rtrees2$votes[,2]), sort(bulletxtrctr::rtrees$votes[,2]))
plot(sort(rtrees3$votes[,2]), sort(bulletxtrctr::rtrees$votes[,2]))
```

```{r}
hamby_comparisons = read.csv("../../../diagnostics-paper/data/raw/hamby-comparisons.csv") %>%
  mutate(bbl1 = str_remove(land_id1, pattern = "Hamby252-|Hamby173-"),
         bbl2 = str_remove(land_id2, pattern = "Hamby252-|Hamby173-")) %>%
  filter(!(bbl1 %in% c("Br6-B2-L1", "Br9-B2-L4", "BrUnk-BB-L2", "BrUnk-BQ-L4") | 
           bbl2 %in% c("Br6-B2-L1", "Br9-B2-L4", "BrUnk-BB-L2", "BrUnk-BQ-L4"))) %>%
  select(-bbl1, -bbl2) %>%
  select(-lag, -abs_lag, -overlap, -signature_length, -flag) %>%
  mutate(case = factor(1:n())) %>%
  rename("samesource" = "same_source") %>%
  select(case, land_id1, land_id2, everything())

set.seed(20170222)
rtrees4 <-
  randomForest(
    factor(samesource) ~ .,
    data = hamby_comparisons %>% select(samesource, rownames(bulletr::rtrees$importance)),
    ntree = 300
  )

set.seed(20140501)
rtrees5 <-
  randomForest(
    factor(samesource) ~ .,
    data = hamby_comparisons %>% select(samesource, rownames(bulletr::rtrees$importance)),
    ntree = 300
  )

# plot votes in a scatterplot
plot(rtrees4$votes, rtrees5$votes)
plot(rtrees4$votes, bulletxtrctr::rtrees$votes)
plot(rtrees5$votes, bulletxtrctr::rtrees$votes)

plot(sort(rtrees4$votes), sort(bulletxtrctr::rtrees$votes))
plot(sort(rtrees5$votes), sort(bulletxtrctr::rtrees$votes))
```

